# Generated by Django 3.1.7 on 2021-03-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mou', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='animal_type',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('BUNNY', 'Bunny'), ('BIRD', 'Bird')], default='CAT', max_length=32, verbose_name='I am a: '),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar1',
            field=models.ImageField(null=True, upload_to='static/images/avatars'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_or_love',
            field=models.CharField(choices=[('FRIENDS', 'Friends'), ('LOVE', 'Love')], default='FRIENDS', max_length=32, verbose_name='I am looking for: '),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=240, null=True, verbose_name='My name is: '),
        ),
    ]
