# Generated by Django 3.1.7 on 2021-03-14 04:17

from django.db import migrations

def create_data(apps, schema_editor):
    Profile = apps.get_model('Mou', 'Profile')
    Profile(animal_type='', name='Moumou', friend_or_love='LOVE', avatar1='').save()


class Migration(migrations.Migration):

    dependencies = [
        ('Mou', '0002_auto_20210314_0411'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]